// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'

// Create Virtual Routes

const LoginRouteLazyImport = createFileRoute('/login')()
const RouteLazyImport = createFileRoute('/')()
const AuthProfileRouteLazyImport = createFileRoute('/_auth/profile')()
const AuthFlockRouteLazyImport = createFileRoute('/_auth/flock')()

// Create/Update Routes

const LoginRouteLazyRoute = LoginRouteLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/route.lazy').then((d) => d.Route))

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const RouteLazyRoute = RouteLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/route.lazy').then((d) => d.Route))

const AuthProfileRouteLazyRoute = AuthProfileRouteLazyImport.update({
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/profile/route.lazy').then((d) => d.Route),
)

const AuthFlockRouteLazyRoute = AuthFlockRouteLazyImport.update({
  path: '/flock',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/flock/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof RouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/flock': {
      preLoaderRoute: typeof AuthFlockRouteLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/profile': {
      preLoaderRoute: typeof AuthProfileRouteLazyImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  RouteLazyRoute,
  AuthRoute.addChildren([AuthFlockRouteLazyRoute, AuthProfileRouteLazyRoute]),
  LoginRouteLazyRoute,
])
