// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const LoginRouteLazyImport = createFileRoute('/login')()
const FlockRouteLazyImport = createFileRoute('/flock')()
const AboutRouteLazyImport = createFileRoute('/about')()
const RouteLazyImport = createFileRoute('/')()

// Create/Update Routes

const LoginRouteLazyRoute = LoginRouteLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/route.lazy').then((d) => d.Route))

const FlockRouteLazyRoute = FlockRouteLazyImport.update({
  path: '/flock',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/flock/route.lazy').then((d) => d.Route))

const AboutRouteLazyRoute = AboutRouteLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about/route.lazy').then((d) => d.Route))

const RouteLazyRoute = RouteLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/route.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof RouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/flock': {
      preLoaderRoute: typeof FlockRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginRouteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  RouteLazyRoute,
  AboutRouteLazyRoute,
  FlockRouteLazyRoute,
  LoginRouteLazyRoute,
])
